Implement test status check in CI workflow
Add a step to check test status and exit if failed

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -118,6 +118,16 @@ jobs:
       - name: Show test status
         run: echo "Test status --> ${{ needs.test.outputs.test-status }}"
 
+      - name: check test status
+        env:
+            result: "${{ needs.test.outputs.test-status }}"
+        run: |
+            if [ $result != "passed"]; then
+              echo "test status: failed"
+              exit 1
+            else
+              echo "test status: passed"
+        
   deploy:
     needs: build
     if: github.ref_name == 'main'
